[[language]]
name = "rust"

[[language]]
name = "go"

[[language]]
name = "python"

[[language]]
name = "elixir"

[[language]]
name = "erlang"

[[language]]
name = "kotlin"

[[language]]
name = "dart"

[[langauge]]
name = "typescript"

[[language]]
name = "latex"

